title: "Scott J. Forman"

menu:
  main:
    - name: Scott J. Forman
      pageref: /
      url: /
      weight: 1
    - name: Macroblog 
      pageref: /macroblog
      url: /macroblog
      weight: 2
    - name: Microblog
      pageref: /microblog
      url: /microblog
      weight: 3
    - name: About
      pageref: /about
      url: /about
      weight: 4
