title: "Scott J. Forman"

menu:
  main:
    - name: Scott J. Forman
      pageref: /
      url: /
      weight: 1
    - name: Posts
      pageref: /posts
      url: /posts
      weight: 2
    - name: About
      pageref: /about
      url: /about
      weight: 3