title: "Scott J. Forman"

menu:
  main:
    - name: Scott J. Forman
      pageref: /
      url: /
      weight: 1
    - name: Feed
      pageref: /feed
      url: /feed
      weight: 2
    - name: About
      pageref: /about
      url: /about
      weight: 4